#!/usr/bin/env python3
"""Generate src/game/assetRegistry.ts from src/app/assets/manifest.json.

Produces static imports for every PNG + JSON atlas so assets stay in
src/app/assets/ (the user's required location) and are bundled by Next.js.
"""
import json, os

MANIFEST = "/home/z/my-project/src/app/assets/manifest.json"
OUT = "/home/z/my-project/src/game/assetRegistry.ts"

with open(MANIFEST) as f:
    m = json.load(f)

char_sheets = m["characterSheets"]
env_sheets = m["environmentSheets"]
all_sheets = m["allSheets"]
anims = m["animations"]

lines = []
lines.append("// AUTO-GENERATED by scripts/gen_asset_registry.py — do not edit by hand.")
lines.append("// Static imports keep PNG + atlas JSON in src/app/assets/ (no duplication).")
lines.append("")

# Imports — one png + one json per sheet
for s in all_sheets:
    lines.append(f"import {s.replace('-', '_')}_png from '@/app/assets/{s}.png';")
    lines.append(f"import {s.replace('-', '_')}_json from '@/app/assets/{s}.json';")
lines.append("")
lines.append("export interface AssetSheet {")
lines.append("  key: string;        // Phaser texture key")
lines.append("  png: string;        // bundled PNG url")
lines.append("  atlas: object;      // parsed atlas JSON (hash format)")
lines.append("  isCharacter: boolean;")
lines.append("}")
lines.append("")
lines.append("export const ASSET_SHEETS: AssetSheet[] = [")
for s in all_sheets:
    var = s.replace("-", "_")
    is_char = "true" if s in char_sheets else "false"
    lines.append(f"  {{ key: '{s}', png: {var}_png, atlas: {var}_json, isCharacter: {is_char} }},")
lines.append("];")
lines.append("")
lines.append("// ── Character animation metadata (frame rates + repeat) ──")
lines.append("// repeat: -1 = loop, 0 = play once")
lines.append("export interface AnimConfig { frameRate: number; repeat: number; }")
lines.append("export const ANIM_DEFAULTS: Record<string, AnimConfig> = {")
lines.append("  idle:        { frameRate: 8,  repeat: -1 },")
lines.append("  walk:        { frameRate: 10, repeat: -1 },")
lines.append("  run:         { frameRate: 13, repeat: -1 },")
lines.append("  jump:        { frameRate: 8,  repeat: 0  },")
lines.append("  attack:      { frameRate: 14, repeat: 0  },")
lines.append("  hurt:        { frameRate: 10, repeat: 0  },")
lines.append("  dead:        { frameRate: 8,  repeat: 0  },")
lines.append("  fall:        { frameRate: 10, repeat: 0  },")
lines.append("  climb:       { frameRate: 8,  repeat: -1 },")
lines.append("  jumpattack:  { frameRate: 14, repeat: 0  },")
lines.append("};")
lines.append("")
lines.append("// Standard animation order for character sheets")
lines.append("export const ANIM_ORDER = [")
for a in ["idle", "walk", "run", "jump", "attack", "hurt", "dead", "fall", "climb", "jumpattack"]:
    lines.append(f"  '{a}',")
lines.append("] as const;")
lines.append("")
lines.append("// Character sheet keys (have animations)")
lines.append("export const CHARACTER_SHEETS: string[] = [")
for s in char_sheets:
    lines.append(f"  '{s}',")
lines.append("];")
lines.append("")
lines.append("// Environment sheet keys (static tile/object collections)")
lines.append("export const ENVIRONMENT_SHEETS: string[] = [")
for s in env_sheets:
    lines.append(f"  '{s}',")
lines.append("];")
lines.append("")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"Wrote {OUT} ({len(all_sheets)} sheets: {len(char_sheets)} character, {len(env_sheets)} environment)")
